# CloudFormation GitSync Deployment Configuration
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/git-sync-concepts-terms.html

template-file-path: ./ec2-autoscaling-alb.yaml

stack-name: autoscale-demo

region: eu-central-1

parameters: {}

tags:
  Project: autoscale-demo
  Environment: demo
  ManagedBy: CloudFormation-GitSync